---

- name: "Ensure SonarQube binary exists"
  stat:
    path: "{{ sonar_daemon_dir }}/sonar"
  register: sonar_binary_stat

- block:
  - name: "Download SonarQube binaries"
    get_url:
      url: "{{ __sonar_download_url }}"
      dest: "/tmp/{{ __sonar_archive }}"
    retries: 5
    delay: 10

  - name: "Expand SonarQube binaries"
    unarchive:
      src: "/tmp/{{ __sonar_archive }}"
      dest: "{{ sonar_install_directory }}"
      owner: "{{ sonar_user }}"
      group: "{{ sonar_group }}"
      copy: no

  - name: "Remove SonarQube archive"
    file:
      path: "/tmp/{{ __sonar_archive }}"
      state: absent
  when: not sonar_binary_stat.stat.exists
